baseURL = 'https://iskolahack.hu/'
title = 'IskolaHACK'
defaultContentLanguage = "hu"

timeout = 3000000

[params]
logo = "logo.png"

[markup.goldmark.renderer]
unsafe = true 

[module]
	[[module.imports]]
	path = "github.com/gergovari/deathrattle"

	[[module.imports]]
	path = "github.com/vyberd/gallery"

[params.mautic]
url = "https://mautic.varigergo.hu"
