[[start]]
	name = "Blog"
	weight = 20
	url = "https://blog.varigergo.hu"

[[start]]
	name = "Közösségi média"
	id = "content"
	weight = 30
[[start]]
	name = "Instagram"
	url = "https://www.instagram.com/iskolahack"
	weight = 10
	parent = "Közösségi média"

